//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsdbMigration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsdbMigration.Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration of a before-after slider revealing the character entities for special Unicode characters.
        /// </summary>
        internal static string AltCharEntities {
            get {
                return ResourceManager.GetString("AltCharEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration of a magnifying glass identifying the extensions of formerly unknown graphics files.
        /// </summary>
        internal static string AltGraphicsIdent {
            get {
                return ResourceManager.GetString("AltGraphicsIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration of SGML to XML conversion.
        /// </summary>
        internal static string AltSgmlToXml {
            get {
                return ResourceManager.GetString("AltSgmlToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics extension identifier.
        /// </summary>
        internal static string GraphicsExtensionIdentifier {
            get {
                return ResourceManager.GetString("GraphicsExtensionIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashiCorp Client Secret.
        /// </summary>
        internal static string HashiCorpClientSecret {
            get {
                return ResourceManager.GetString("HashiCorpClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGML to XML well-formed.
        /// </summary>
        internal static string SgmlToXmlWellFormed {
            get {
                return ResourceManager.GetString("SgmlToXmlWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search XML for special characters and convert them into corresponding character entities.
        /// </summary>
        internal static string TooltipCharEntities {
            get {
                return ResourceManager.GetString("TooltipCharEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify the file-extensions of unidentified graphics files.
        /// </summary>
        internal static string TooltipGraphicsIdent {
            get {
                return ResourceManager.GetString("TooltipGraphicsIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert SGML files to well-formed XML using the Omnimark script.
        /// </summary>
        internal static string TooltipSgmlToXml {
            get {
                return ResourceManager.GetString("TooltipSgmlToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML character entity sanitizer.
        /// </summary>
        internal static string XmlCharacterEntitySanitizer {
            get {
                return ResourceManager.GetString("XmlCharacterEntitySanitizer", resourceCulture);
            }
        }
    }
}
